title: かがりび
description: >
  かがりびはなと氏のブログみたいなものです。
baseurl: ""
url: "http://kagaribi.gentoo.app"

typekit:
  jstag: |
    <script>
      (function(d) {
        var config = {
          kitId: 'tet4iux',
          scriptTimeout: 3000,
          async: true
        },
        h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
      })(document);
    </script>
  csstag: <link rel="stylesheet" href="https://use.typekit.net/bkl0chp.css">

author:
  name: Yu Uchino
  email: info@gentoo.app
  github: mizphses

paginate: 3
paginate_path: page:num

sass:
  style: compressed 

gems:
  - jekyll-paginate
  - jekyll-feed